module.exports = {
	things: [
		{
			key: 'my-aqi',
			airNowData: [
				{
					AQI: 58,
					Category: {
						Name: 'Moderate',
						Number: 2,
					},
					DateObserved: '2023-06-08 ',
					HourObserved: 10,
					Latitude: 39.9003,
					LocalTimeZone: 'MST',
					Longitude: -105.042,
					ParameterName: 'O3',
					ReportingArea: 'Denver-Boulder',
					StateCode: 'CO',
				},
				{
					AQI: 23,
					Category: {
						Name: 'Good',
						Number: 1,
					},
					DateObserved: '2023-06-08 ',
					HourObserved: 10,
					Latitude: 39.9003,
					LocalTimeZone: 'MST',
					Longitude: -105.042,
					ParameterName: 'PM2.5',
					ReportingArea: 'Denver-Boulder',
					StateCode: 'CO',
				},
				{
					AQI: 27,
					Category: {
						Name: 'Good',
						Number: 1,
					},
					DateObserved: '2023-06-08 ',
					HourObserved: 10,
					Latitude: 39.9003,
					LocalTimeZone: 'MST',
					Longitude: -105.042,
					ParameterName: 'PM10',
					ReportingArea: 'Denver-Boulder',
					StateCode: 'CO',
				},
			],
			iqAirData: {
				data: {
					city: 'Longmont',
					country: 'USA',
					current: {
						pollution: {
							aqicn: 1,
							aqius: 4,
							maincn: 'p2',
							mainus: 'p2',
							ts: '2023-06-08T17:00:00.000Z',
						},
						weather: {
							hu: 48,
							ic: '01d',
							pr: 1014,
							tp: 22,
							ts: '2023-06-08T17:00:00.000Z',
							wd: 70,
							ws: 2.06,
						},
					},
					location: {
						coordinates: [-105.10193, 40.16721],
						type: 'Point',
					},
					state: 'Colorado',
				},
				status: 'success',
			},
		},
	],
	webmentions: [
		{
			id: 'in:foo',
			created: new Date().toISOString(),
			target: 'https://tbeseda.com/articles/1986/11/test',
			source: 'https://arc.codes/docs/en/get-started/quickstart',
			targetPath: '/articles/1986/11/test',
			sourceAuthor: 'Alice',
			sourceTitle: 'Architect',
			request: { headers: {}, body: {} },
		},
		{
			id: 'in:bar',
			created: new Date().toISOString(),
			target: 'https://tbeseda.com/articles/1986/11/test',
			source: 'https://enhance.dev/docs/',
			targetPath: '/articles/1986/11/test',
			sourceTitle: 'Enhance',
			request: { headers: {}, body: {} },
		},
		{
			id: 'in:baz',
			created: new Date().toISOString(),
			target: 'https://tbeseda.com/articles/1986/11/test',
			source: 'https://begin.com',
			targetPath: '/articles/1986/11/test',
			request: { headers: {}, body: {} },
		},
	],
}
