module.exports = {
  content: ['./src/views/**/*.mjs'],
  theme: {
    extend: {
      colors: {
        'begin-coral': '#fd6d6d',
        'begin-orange': '#fe8e20',
        'green-pickup': '#007932',
        'CO-blue': {
          DEFAULT: '#002147',
          50: '#00418C',
          100: '#003D84',
          200: '#003675',
          300: '#002F66',
          400: '#002856',
          500: '#002147',
          600: '#001A38',
          700: '#001328',
          800: '#000C19',
          900: '#00050A',
        },
      },
    },
    fontFamily: {
      // https://systemfontstack.com/
      sans: [
        '-apple-system',
        'BlinkMacSystemFont',
        '"avenir next"',
        'avenir',
        '"segoe ui"',
        '"helvetica neue"',
        'helvetica',
        'Ubuntu',
        'roboto',
        'noto',
        'arial',
        'sans-serif',
      ],
      serif: [
        '"Iowan Old Style"',
        '"Apple Garamond"',
        'Baskerville',
        '"Times New Roman"',
        '"Droid Serif"',
        'Times',
        '"Source Serif Pro"',
        'serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
      ],
      mono: [
        'Menlo',
        'Consolas',
        'Monaco',
        '"Liberation Mono"',
        '"Lucida Console"',
        'monospace',
      ],
    },
  },
  plugins: [],
};
