---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5cdaf2d790db6d0015dfb241/webhook/forestry
sections:
- type: document
  path: config.yaml
  label: Config
  templates:
  - config
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: document
  path: content/elements.md
  label: Elements
  templates:
  - elements
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.47
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.47'
